### ISSUE TITLE
Improvements and Optimizations

### ISSUE THREAD

**Issue by GabrielOsvair** [cdverrett94/overhead-tile-fade-for-all-tokens#4]
(Google Translator) There could be in the module settings tab a general setting, to affect all tiles. And the main point would be that although I love the functionality of tiles being transparent if any token is down, if a token is behind a tree trunk, its crowns are transparent and reveal that there is something there (even the token cannot to see). Would there be a tile mode with the type "treetops" so that this doesn't happen?
![image](https://user-images.githubusercontent.com/67530921/131517015-71138e3a-1872-4acf-ad06-5a4881b4af76.png)
![image](https://user-images.githubusercontent.com/67530921/131517067-3b0bcd3f-28de-4e1c-8e0d-2fcd29533dc5.png)

**Comment by GabrielOsvair** [comment]
(Google Translator) NOTE: I noticed that there are settings so that enemy/neutral tokens don't make tiles transparent to players, but I was thinking about using sight lines to calculate when to hide or not a tile. I know using sight lines and the like must be difficult and a lot more complex, so anyways it becomes a possible feature someday.

**Comment by cdverrett94** [comment]
Good evening! I have changed how the settings are done. Instead of it being off or using token disposition, the new options are as follows:
- Foundry Default - uses the default foundry method where the tile is faded for only the token under the tile
- All - Fade the tile for all tokens regardless of visibility, hidden status, or disposition
- By Disposition - fade the tile if a token that matches the selected disposition and hidden status in the settings
- By Visibility - fade the tile as long as the controllers token has visibility on the token under the tile. 

I imagine this new By Visibility mode will be the norm and at this point, I'm not entirely certain, why I didn't do by visibility in the first place. I guess I assumed it would be much more complicated than I thought. Let me know once you've tried it if that's what you are looking for!

**Comment by GabrielOsvair** [comment]
(Google Translator) It looks good! Sometimes you need to move the token one square to make the tile transparent or after selecting a token being GM but it works!
   A request: It would be great if it had a macro to change all these settings of all selected tiles! There is a macro in the compendium but it doesn't seem to work...

Thanks for the module and don't abandon it!

**Comment by GabrielOsvair** [comment]
(Google Translator) NOTE: A hidden token still hides the tile if I am GM, but on player screen it doesn't occur.

**Comment by cdverrett94** [comment]
I'll see if there's anything I can do about the having to move the token when switching tokens as a GM. 

There is a Macro to change all settings on all controlled tiles. I just tested it and it seems to work on my end. Looks like someone 2 of the "update all" got in the compendium, so make sure to try the other one. I'll post an update to remove the incorrect duplicate. 

As far as hidden tokens fading a tile for a GM always, this sounds like the correct behavior or else the GM could lose tokens. If the player view is correct based on settings, then I don't think there's anything for me to do.

**Comment by GabrielOsvair** [comment]
(Google Translator) I looked it up here and the second macro for general setting works, about setting for hidden tokens really makes sense for the GM view. Thanks for your attention, you are amazing!

**Comment by cdverrett94** [comment]
Just did a new release to fix the duplicate macros in the compendium and the issue where you had to move the token to get the right tiles faded. This also fixes an issue players would end up having right as the gain/lose visibility on a token. Thanks for the report! Hope this works well for you.
